#!/bin/sh

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# read inputs
source=$1
payload=$(mktemp request.XXXXXX)
cat > $payload <&0

# parse parameters
name=$(jq -r '.source.name // ""' < $payload)

if [ -z "$name" ]; then
    echo "Invalid payload (missing name)"
    exit 1
fi

AWS_ACCESS_KEY_ID=$(jq -r '.source.access_key_id // ""' < $payload)
AWS_SECRET_ACCESS_KEY=$(jq -r '.source.secret_access_key // ""' < $payload)
AWS_DEFAULT_REGION=$(jq -r '.source.region // ""' < $payload)

# leave unset to support IAM roles
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
fi

[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

details=$(mktemp details.XXXXXX)

if ! aws ecr describe-repositories --repository-names ${name} > $details; then
    echo "Creating ${name} repository"
    aws ecr create-repository --repository-name ${name} > $details
else
    echo "Repository ${name} already exists"
fi


result="$(jq -n "{version:{name:\"${name}\"}}")"
echo "$result" | jq -s add >&3
